version: '{build}'
image: Visual Studio 2017
configuration: Release
environment:
  sourceFolder: src
  projectName: Client
  solutionName: tdl.sln
  api_key:
    secure: IiY1EfTKNqTmaGPnhcdfe7HlRBL2UtwFPvwz3QyW9QZiJ6wtfgeH/WlIWuzF6Lrf
  packageName: TDL.Client
  PYTHON: C:\\Python37

install:
- cmd: git submodule update --init --recursive
  
before_build:
- ps: >-
    nuget restore

    if ($env:APPVEYOR_REPO_TAG -eq "true" -and
        $env:APPVEYOR_REPO_TAG_NAME.StartsWith("v0.")) {
      # Patch NuGet package version into .nuspec file
      $nuspecPath = "$($env:APPVEYOR_BUILD_FOLDER)\$($env:sourceFolder)\$($env:projectName)\$($env:projectName).nuspec"
      $nuspec = [xml](Get-Content $nuspecPath)
      $nuspec.package.metadata.version = "$($env:APPVEYOR_REPO_TAG_NAME.Trim("v"))"
      $nuspec.Save($nuspecPath)
    }
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build:
  project: $(solutionName)
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

test_script:
- run-tests.cmd	

deploy:
- provider: NuGet
  api_key: $(api_key)
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
    APPVEYOR_REPO_TAG_NAME: /v0.*/
